# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: k8s-toolbox
version: 2

snapshot:
  version_template: "{{ .Tag }}-next"

# changelog:
#   sort: asc
#   use: github-native

builds:
  - skip: true

dockers:
  - image_templates:
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "oryd/{{ .ProjectName }}:{{ .ShortCommit }}-amd64"
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: "docker/Dockerfile"
  - image_templates:
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "oryd/{{ .ProjectName }}:{{ .ShortCommit }}-arm64"
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
    dockerfile: "docker/Dockerfile"

docker_manifests:
  - name_template: "oryd/{{ .ProjectName }}:{{ .Tag }}"
    id: "tag"
    image_templates:
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-arm64"
  - name_template: "oryd/{{ .ProjectName }}:latest"
    id: "latest"
    image_templates:
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-arm64"

release:
  prerelease: auto
  name_template: "{{ .Tag }}"