---
name: 'Build and Scan docker image'
description: 'Builds and scans docker image'
inputs:
  labels:
    required: false
    default: '[]'
    description: Set of image labels
  tags:
    required: true
    description: Set of image tags
runs:
  using: "composite"
  steps:
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3    # Updated from v1 to v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated from v1 to v3

    - name: Build
      uses: docker/build-push-action@v5    # Updated from v2 to v5
      with:
        context: ./docker
        push: false
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        load: true

    - name: Anchore Scanner
      uses: anchore/scan-action@v3
      if: always()
      id: grype-scan
      with:
        image: oryd/k8s-toolbox:sha-${{ steps.vars.outputs.sha_short }}
        fail-build: true
        severity-cutoff: high
        acs-report-enable: true

    - name: Inspect action SARIF report
      shell: bash
      if: always()
      run: |
        echo "::group::Anchore Scan Details"
        jq '.runs[0].results' ${{ steps.grype-scan.outputs.sarif }}
        echo "::endgroup::"

    - name: Trivy Scanner
      if: always()
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: oryd/k8s-toolbox:sha-${{ steps.vars.outputs.sha_short }}
        format: 'table'
        exit-code: 42
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Dockle Linter
      uses: erzz/dockle-action@v1.3.1
      if: always()
      with:
        image: oryd/k8s-toolbox:sha-${{ steps.vars.outputs.sha_short }}
        exit-code: 42
        failure-threshold: fatal