name: Validation - GHA Linter
on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  validate:
    name: Validate GHA
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
        id: filter
        with:
          base: master
          filters: |
            workflows:
              - '.github/**'
      - name: actionlint
        if: ${{ steps.filter.outputs.workflows == 'true' }}
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2