name: Licenses

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: make licenses
