name: Validation - Renovate
on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches:
      - master

jobs:
  validate:
    name: Validate Renovate
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group' || github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          base: master
          filters: |
            renovate:
              - 'renovate.json'
      - name: Validate Renovate config
        if: ${{ steps.filter.outputs.renovate == 'true' }}
        uses: suzuki-shunsuke/github-action-renovate-config-validator@ee9f69e1f683ed0d08225086482b34fc9abe9300 # v2.1.0
