name: Validation - Renovate
on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches:
      - master

jobs:
  validate:
    name: Validate Renovate
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group' || github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
        id: filter
        with:
          base: master
          filters: |
            renovate:
              - 'renovate.json'
      - name: Validate Renovate config
        if: ${{ steps.filter.outputs.renovate == 'true' }}
        uses: suzuki-shunsuke/github-action-renovate-config-validator@ee9f69e1f683ed0d08225086482b34fc9abe9300 # v2.1.0
